### ISSUE TITLE
Massive memory leak

### ISSUE THREAD

**Issue by Presty1** [ESX-Org/esx_menu_default#16]
Please fix this issue. Its causing a massive memory leak if I scroll really fast or just use the menu in general. And my MB starts going up and over 50 mb and then a resource time warning happens.

**Comment by benzon** [comment]
nothing new just a duplicate of #15 

Reported back in January but not sure these bug report are being read :)

**Comment by Jason1123** [comment]
This has been such a huge issue sense this has been released and the dumb thing about it is that the developer of this script never responds to bugs of a script he made. I have been looking and trying to find a fix but everything I try to do does not fix it. I got the main menus to not do it anymore but the esx_skin menu for this is causing soo much lag and to even create a character it takes like 20 minutes because of this lag. I managed to get it to run a little better but the lag is still there.
